name: diff-ii-da
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipdb
  - flake8
  - ipykernel
  - pytest
  - pytest-env
  - tqdm
  - numpy
  - pytorch>=1.11.0
  - torchvision>=0.12.0
  - nvidia::cudatoolkit
  - wandb
  - tensorboard
  - transformers==4.36.2
  - diffusers==0.25.1
  - accelerate==0.25.0
  - xformers::xformers
  - seaborn
  - cuda-nvcc
  - pip:
    - huggingface_hub==0.25.2
    - git+https://github.com/modestyachts/ImageNetV2_pytorch
    - datasets
    - git+https://github.com/openai/CLIP.git
    - open_clip_torch
    - peft==0.7.1
    - pytorch-warmup
    - lpips
    - git+https://github.com/ildoonet/cutmix.git
variables:
  CACHE_NUMBER: 0
